#! /bin/sh

get_lang() {
#	str="(\$1==\"$1\"){flag=1} (\$1==\"Retrieved\"&&\$2==\"from\"||\$1~/-----/){flag=0} {if (flag==1) print \$0} "
#	echo $str
#	[ $1 = "Russian" ] && \
		gawk "(\$1==\"$1\"){flag=1} (\$1==\"Retrieved\"&&\$2==\"from\"||\$1~/-----/){flag=0} {if (flag==1) print \$0} " && return
#	[ $1 = "French" ] && \
#		gawk '($1=="French"){flag=1} ($1=="Retrieved"&&$2=="from"||$1~/-----/){flag=0} {if (flag==1) print $0} ' && return
	
#	gawk '($1=="English"){flag=1} ($1=="Retrieved"&&$2=="from"||$1~/-----/){flag=0} {if (flag==1) print $0} '	
}

_word=`wget "https://en.wiktionary.org/w/index.php?title=$2&printable=yes" 2>/dev/null -O - \
	| w3m -dump -no-graph -T text/html \
	| get_lang English \
	| grep -Poi "\* $1: (.*?)(?=\s*\*|$)" \
	| fzf --layout=reverse \
	| grep -Po '.*:\s+(.*?)(?=\s+\()' \
	| awk -F": " '{print $2}'`

[ -z $_word ] && exit

_url=`echo "https://en.wiktionary.org/w/index.php?title=$_word&printable=yes" | sed 's/ /%20/g'`

#lynx "$_url"

wget "$_url" 2>/dev/null -O - \
	| w3m -dump -no-graph -T text/html \
	| get_lang "$1" \
	| less

