#! /bin/sh

dump()      { w3m "$1" -dump -no-graph -T text/html; }
sanitize()  { sed 's/о́/о/g; s/а́/а/g'; }
pick_word() { sanitize | fzf --layout=reverse; }

parse_section() {
	awk "(\$1==$1){flag=1} (\$1==\"Retrieved\"&&\$2==\"from\"||\$1~/-----/){flag=0} {if (flag==1) print \$0}"
}

build_url() {
	#echo "https://en.wiktionary.org/w/index.php?title=$1"
	echo "https://en.wiktionary.org/wiki/$1"
}

#url=`build_url "$2"`

word=`dump `build_url "$2"` \
	| parse_section "English" \
	| grep -Poi "\* $1: (.*?)(?=\s*\*|$)" \
	| pick_word \
	| grep -Po '.*:\s+(.*?)(?=\s+\()' \
	| awk -F": " '{print $2}'`

[ -z "$word" ] && exit

url=`build_url "$word"`

dump "$url" | parse_section "$1" | less

